tideService: "grib"
windService: "grib"
gribFetcher: "OpenSkiron"
tideTimeService: "admiralty"
tideGribConf:
  gribReader: "NetCDFGribReader"
  filePath: "gribFiles/Cherbourg_4km_WRF_WAM.grb"
  latVarName: "TwoD/LatLon_99X119-49p73N-1p347W/lat"
  lonVarName: "TwoD/LatLon_99X119-49p73N-1p347W/lon"
  timeVarName: "TwoD/LatLon_99X119-49p73N-1p347W/time"
  uTideVarName: "TwoD/LatLon_99X119-49p73N-1p347W/u-component_of_current_surface"
  vTideVarName: "TwoD/LatLon_99X119-49p73N-1p347W/v-component_of_current_surface"
windGribConf:
  gribReader: "NetCDFGribReader"
  filePath: "gribFiles/Cherbourg_4km_WRF_WAM.grb"
  latVarName: "TwoD/LatLon_76X92-49p73N-1p324W/lat"
  lonVarName: "TwoD/LatLon_76X92-49p73N-1p324W/lon"
  timeVarName: "TwoD/LatLon_76X92-49p73N-1p324W/time"
  uWindVarName: "TwoD/LatLon_76X92-49p73N-1p324W/u-component_of_wind_height_above_ground"
  vWindVarName: "TwoD/LatLon_76X92-49p73N-1p324W/v-component_of_wind_height_above_ground"
