name: Backend Continuous Integration
on:
  pull_request:
    paths:
      - "backend/**"
jobs:
  build-test-lint:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
