name: Backend Continuous Integration
on:
  pull_request:
    paths:
      - "backend/**"
jobs:
  build-test-lint:
    name: Test
    runs-on: ubuntu-latest

    env:
      ADMIRALTY_API_KEY: ${{ secrets.TEST_ADMIRALTY_API_KEY }}

    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and Test
        run: ./gradlew build
