name: Frontend Continuous Integration
on:
  pull_request:
    paths:
        - 'app/**'
jobs:
  build-test-lint:
    name: Build, Test & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: yarn install
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
