name: Frontend Continuous Integration
on:
  pull_request

jobs:
  lint: 
    name: Build, Test & Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Change to app directory
      run: cd app
    - name: Build
      run: yarn install
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
