name: Continuous Integration
on:
  pull_request

jobs:
  lint: 
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: yarn install
    - name: Lint
      run: yarn lint
